### ISSUE TITLE
Feedback on initial Whitepaper

### ISSUE THREAD

**Issue by Cashmaney** [GridlockNetwork/Whitepaper#1]
Hey,

Just wanted to add my 2 cents from the whitepaper. Mainly things that jumped out to me when reading. I like the idea, and I think you guys have a cool plan, but there are a lot of complex issues that I (at least from reading the materials available) am not sure you're considering. The main TL;DR is that to prove that you guys can pull something like this off it would take a much deeper dive into the specifics of the crypto and communication protocols. Transcribing the stuff I wrote down while reading the proposal (in no particular order):

**General** 

- Did you guys look into what it means to hold shares of keys from a legal standpoint? Would GridlockNetwork be regarded as a custodian? Would holding shares of private keys that hold cryptocurrencies require you to be a qualified custodian? Is GridlockNetwork a legal entity? 

**UX/Usability**

- If you have multiple actors that are possibly offline, how do you handle synchronizing all the parties? Would you just assume the key owner has to coordinate all the parties?

- How long would a single transaction take? Does this mean the user has to be online for the entire time? What about latency considerations for mobile connections?

**Cryptostuff**

- Without a detailed design of end-to-end communications. I'm not fully convinced you can pull off what you're suggesting here.

- Are you going to support ECDSA? EdDSA? Other?

- How are you planning to handle the specifics of implementing a cryptographic algorithm on-chain? Specifically, the lack of randomness and the lack of time? Are you planning to use trusted oracles? If your answer to this includes "we use a trusted 3rd party", then doesn't this trusted 3rd party become a single-point-of-failure that invalidates your security assumptions? (i.e. would the algorithm be resistant to a hostile oracle?)

- I think for a system like this minimizing the amount of rounds for the interactive MPC protocol, or even implementing a non interactive protocol would go along way in reducing protocol complexity (though setting up a non-interactive protocol has it's own set of challenges). See: https://eprint.iacr.org/2020/492.pdf (among others)

- Considering (at the moment, and by design), the all nodes on the blockchain store all the data, and perform all calculations, why would you want to store multiple shares on-chain?

- The scope of this project is much too large. There are multiple start-ups working full time on projects with a smaller scope than this (see: Zengo, Curv, even Fireblocks to an extent). If you want to have any chance of success, start super small and focused. I would remove the TSS completely, and only later on think of adding basic 2-of-2 support.
You're trying to tackle a difficult, unsolved (that I know of, anyway) issue already, which is using a blockchain as a KMS. Solve that first and think of adding complexity later.

**Comment by DerekfromMadison** [comment]
Thanks Cashmaney, we appreciate the input. I'll provide high-level responses here and can expand further via direct communication. 

#### **General**

**what about legal concerns?...**

Any key share t or less is just a collection of useless data and therefore non-custodial. People might contest that point, but the burden of proof is on the ability to do anything with that data. Additionally, the core product is simply a storage mechanism that is never at fault for actions taken outside of its confines. It's the *use* of funds that may be questioned. That use is outside the purview of the storage container.

#### **UX/Usability**

**Synchronizing offline parties...**

For usability, we would direct users to use a majority of highly available options as an ideal setup. Part of the service offered is easy onboarding for various storage mechanisms. That said, there are continuing improvements to TSS algorithms, and the current state-of-the-art is incorporating non-interactive functionality. See https://eprint.iacr.org/2020/540.pdf. We plan to adopt these new improvements ASAP. 

**What about transaction speed?...**

Transaction signing will vary depending on the number of participants, network speed, etc., but even at worst case, the time required is counted in seconds. We can conservatively say that transaction signing will take an average of 10 seconds and be happy with that considering that Bitcoin has a 10 minute block time and Ethereum is at least 10 seconds. 

#### **Cryptostuff**

**Are you going to support ECDSA? EdDSA? Other?**

We would start with ECDSA , due to its prevalence, and build from there. 

**How are you planning to handle the specifics of implementing a cryptographic algorithm on-chain?** 

Randomness is important and will continue to be an ongoing point of discussion in cryptography for the foreseeable future. That said, for practical purposes, we don't need a spherical cow. The idea of perfect trustless randomness is the holy grail that doesn't exist. We should not be asking "How do we build perfect trustless randomness?" but rather "How do we add a little bit of trust back into this system". People want something that works given a reasonable level of trust. Even blockchain is based on trust, the trust that all actors will behave in their ideal best interest. It's reasonable to make that assumption given the mechanisms and game theory provided, but it is trust nonetheless. 

As for oracles as a point of failure, a corrupt oracle might be a problem, but we can engineer solutions to minimize the possibility and impact of those problems. It's time we get some engineers on board and start making products that are *practical* rather than just theoretical. 

**Why multiple shares on-chain?**

We want to build for cases where all nodes do not share the same key. Once the Secret Network is more mature, it should not require too much more effort to split nodes into secret pools where each pool shares a distinct key. 

**The scope of this project is much too large.**

Our initial prototyping work is focusing on a product without TSS. It will be the skeleton for a more robust product that can provide a fully secure and private solution. As you mentioned, multiple companies are working on similar projects. We don't have to re-invent the wheel for TSS; rather we can build off the work of others and add-on the TSS portion with relative ease. Famous last words? Let's hope not.
